// <auto-generated />
namespace Wiser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class testing0syntax : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testing0syntax));
        
        string IMigrationMetadata.Id
        {
            get { return "201907082002221_testing=0syntax"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
